#!/bin/bash
#SBATCH -J myjob                         # job name
#SBATCH -o myjob.o%j                     # output file name (%j expands to jobID)
#SBATCH -e myjob.e%j                     # error  file name (%j expands to jobID)
#SBATCH -N 2                             # total number of nodes requested
#SBATCH -n 2                             # total number of mpi tasks requested
#SBATCH -p development                   # queue (partition)
#SBATCH -t 01:30:00                      # run time (hh:mm:ss) - 1.5 hours

ibrun hostname                           # runthe hostname command in eash MPI task
ibrun ./a.out

